# Generated by Django 3.0.2 on 2020-04-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('curr_calories', models.IntegerField(default=0)),
                ('total_calories', models.IntegerField(default=2000)),
                ('calories_exceeded', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200)),
                ('calories', models.IntegerField(max_length=99999)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendly_clone.User')),
            ],
        ),
    ]
