# Generated by Django 3.0.2 on 2020-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calories_exceeded',
            field=models.BooleanField(default=False),
        ),
    ]
