# Generated by Django 3.0.2 on 2020-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly_clone', '0002_auto_20200423_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=100),
        ),
    ]
